---
# file: roles/jupyter/tasks/main.yml

- name: make sure necessary packages are installed
  apt: name={{item}} state=present update_cache=yes
  with_items: "{{jupyter_pkgs}}"
  tags: jupyter

- name: Install pip
  shell: >
    curl https://bootstrap.pypa.io/get-pip.py > /dev/shm/get-pip.py &&
    python3 /dev/shm/get-pip.py ;
    rm /dev/shm/get-pip
  args:
    creates: /usr/local/bin/pip3
  tags: jupyter

- name: install npm package configurable-http-proxy
  npm: name=configurable-http-proxy global=yes state=present
  tags: jupyter

- name: add jupyter group
  group: name={{jupyterhub_user}} state=present
  tags: jupyter

- name: add jupyter user
  user:
    name: "{{jupyterhub_user}}"
    state: present
    groups: "{{jupyterhub_user}},shadow"
    password: "{{jupyterhub_user_password}}"
  tags: jupyter

- name: create jupyterhub folder in etc
  file:
    path: /etc/jupyterhub
    state: directory
    mode: "0755"
    owner: "{{jupyterhub_user}}"
    group: "{{jupyterhub_user}}"
  tags: jupyter

- name: copy jupyterhub sudospawner sudo config
  template: src=sudoers_jupyterhub.j2 dest=/etc/sudoers.d/jupyterhub mode=0440 owner=root group=root
  tags: jupyter

- name: install jupyter, jupyterhub, sudospawner via pip3
  pip: executable=pip3 name={{item}} state=latest
  with_items:
    - jupyter
    - notebook
    - jupyterhub
    - sudospawner
  tags: jupyter

- name: Check to see if config file exists
  stat: path=/etc/jupyterhub/jupyterhub_config.py
  register: config_exists
  tags: jupyter

- name: configure jupyterhub
  command: /usr/local/bin/jupyterhub --generate-config chdir=/etc/jupyterhub/ creates=/etc/jupyterhub/jupyterhub_config.py
  when: config_exists.stat.exists == False
  tags: jupyter

- name: set jupyterhub admin user
  lineinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    line: "c.Authenticator.admin_users = {{jupyterhub_admin_users | to_json}}"
  tags: jupyter

- name: set jupyterhub create users
  lineinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    line: "c.LocalAuthenticator.create_system_users = {{True if jupyterhub_create_system_users else False}}"
  tags: jupyter

- name: set IP address
  lineinfile: dest=/etc/jupyterhub/jupyterhub_config.py line="c.JupyterHub.hub_ip = '{{jupyterhub_ip}}'"
  tags: jupyter

- name: set IP address
  lineinfile: dest=/etc/jupyterhub/jupyterhub_config.py line="c.JupyterHub.ip = '{{jupyterhub_ip}}'"
  tags: jupyter

- name: set IP address
  lineinfile: dest=/etc/jupyterhub/jupyterhub_config.py line="c.JupyterHub.proxy_api_ip = '{{jupyterhub_ip}}'"
  tags: jupyter

- name: install jupyterhub systemd unit
  copy:
    src: jupyterhub.systemd
    dest: /lib/systemd/system/jupyterhub.service
    owner: root
    group: root
    mode: 0644
  tags: jupyter

- name: "Ensure jupyterhub var dir exists"
  file:
    path: /var/lib/jupyterhub
    state: directory
  tags: jupyter


- name: "Ensure jupyterhub is started"
  service:
    name: jupyterhub
    state: restarted
    enabled: yes
  tags: jupyter


- name: "Add jupterhub to nginx sites"
  template:
    src: nginx_jupyterhub.j2
    dest: /etc/nginx/sites-available/jupyterhub
    owner: root
    group: root
    mode: 0644
  when: jupyterhub_nginx
  tags: jupyter
